version = 1

[[route]]
id = "6281d965-093e-4aaa-9ce0-2f67b95c8bbc"
path = "T-physics/L-emergence/L-patchy-particle-emergence/E-04-experimental-laboratory"
format = "mp4"
uri = "https://youtu.be/kJ7cs7i9iqU"
