version = 1

[[route]]
id = "2a05068f-d48c-4fdd-915c-778bc8f42211"
path = "T-computer-science/L-composite/F-01-carbon-binder"
format = "md"
location = "T-computer-science/L-composite/F-01-carbon-binder.md"

[[route]]
id = "24309c9a-2e80-47b9-884b-cc9801178c0d"
path = "T-computer-science/L-composite/F-02-type-binder"
format = "md"
location = "T-computer-science/L-composite/F-02-type-binder.md"

[[route]]
id = "371342c0-401f-4d34-a537-439386bf9f7c"
path = "T-computer-science/L-composite/F-03-query-binder"
format = "md"
location = "T-computer-science/L-composite/F-03-query-binder.md"

[[route]]
id = "42292902-3874-4d54-87ec-0e1b7362af13"
path = "T-computer-science/L-composite/F-04-TLF-composite"
format = "md"
location = "T-computer-science/L-composite/F-04-TLF-composite.md"

[[route]]
id = "499ff1af-eed7-425d-9fed-e357ec2e0b97"
path = "T-computer-science/L-functions/F-01-function"
format = "md"
location = "T-computer-science/L-functions/F-01-function.md"

[[route]]
id = "9d406912-c737-416c-94f2-4edb90db3ee7"
path = "T-computer-science/L-functions/F-02-execution"
format = "md"
location = "T-computer-science/L-functions/F-02-execution.md"

[[route]]
id = "1e650360-f987-42c8-ab37-d2e928b82b32"
path = "T-computer-science/L-functions/F-03-function-network"
format = "md"
location = "T-computer-science/L-functions/F-03-function-network.md"

[[route]]
id = "7bd2455a-1fe5-4972-9c36-78d6a4f0df9b"
path = "T-computer-science/L-functions/F-04-function-natural-wrappers"
format = "md"
location = "T-computer-science/L-functions/F-04-function-natural-wrappers.md"

[[route]]
id = "9e9629bd-eb94-40fc-ba6e-922420cd13f7"
path = "T-computer-science/L-functions/Fd-function-orchestration"
format = "md"
location = "T-computer-science/L-functions/Fd-function-orchestration.md"

[[route]]
id = "f776b280-d6fa-4bbd-b213-4978165137eb"
path = "T-computer-science/L-inference/F-01-theorem"
format = "md"
location = "T-computer-science/L-inference/F-01-theorem.md"

[[route]]
id = "08113955-1ff0-4131-877e-4466e614bd1b"
path = "T-computer-science/L-inference/F-02-agents"
format = "md"
location = "T-computer-science/L-inference/F-02-agents.md"

[[route]]
id = "bb00a29b-d851-4395-9e20-bce895bb379e"
path = "T-computer-science/L-inference/F-03-conclusions"
format = "md"
location = "T-computer-science/L-inference/F-03-conclusions.md"

[[route]]
id = "39b82207-e234-4352-bc3c-01d84362a7eb"
path = "T-computer-science/L-semantics/F-01-data-semantics"
format = "md"
location = "T-computer-science/L-semantics/F-01-data-semantics.md"

[[route]]
id = "5da0c374-473b-40d6-a7dd-659dc4f5211d"
path = "T-computer-science/L-semantics/F-02-json-representation"
format = "md"
location = "T-computer-science/L-semantics/F-02-json-representation.md"

[[route]]
id = "0fa7348d-69f2-487a-a684-71eada16a96d"
path = "T-computer-science/L-semantics/F-03-agent-prompt"
format = "md"
location = "T-computer-science/L-semantics/F-03-agent-prompt.md"

[[route]]
id = "ff73c9d4-922b-471e-beb5-3dde7c4a415f"
path = "T-computer-science/T-mechanics/L-sparse-ticker-state/F-sparse_ticker_state_ledger"
format = "ipynb"
location = "T-computer-science/T-mechanics/L-sparse-ticker-state/F-sparse_ticker_state_ledger.ipynb"

[[route]]
id = "ff73c9d4-922b-471e-beb5-3dde7c4a415f"
path = "T-computer-science/T-mechanics/L-sparse-ticker-state/F-sparse_ticker_state_ledger"
format = "md"
location = "T-computer-science/T-mechanics/L-sparse-ticker-state/F-sparse_ticker_state_ledger.md"

[[route]]
id = "f2b1b8c2-86c8-484c-bb44-92c711ac607e"
path = "T-computer-science/T-networking/L-DNS/F-01-introduction"
format = "md"
location = "T-computer-science/T-networking/L-DNS/F-01-introduction.md"

[[route]]
id = "ff647a5d-44f0-42af-9f01-abcadd04fb37"
path = "T-math/L-division/F-01-introduction"
format = "md"
location = "T-math/L-division/F-01-introduction.md"

[[route]]
id = "1497eefc-aa3d-4444-a426-9ccb0410b0bf"
path = "T-math/L-exponential-phase/F-01-branching-depth-resolution"
format = "md"
location = "T-math/L-exponential-phase/F-01-branching-depth-resolution.md"

[[route]]
id = "ff7c99b6-ce1f-4973-9d3c-89f1f12a1f69"
path = "T-math/L-exponential-phase/F-02-discrete-phase-rulers"
format = "md"
location = "T-math/L-exponential-phase/F-02-discrete-phase-rulers.md"

[[route]]
id = "f1504ef9-d65e-4753-8032-27672b2ffa6a"
path = "T-math/L-exponential-phase/F-03-hidden-generators"
format = "md"
location = "T-math/L-exponential-phase/F-03-hidden-generators.md"

[[route]]
id = "c6d131b8-0ba5-4ab4-bfdb-c871b95b98e6"
path = "T-math/L-exponential-phase/Fd-exponential-phase-visual-notebook"
format = "ipynb"
location = "T-math/L-exponential-phase/Fd-exponential-phase-visual-notebook.ipynb"

[[route]]
id = "edba87bc-3359-4ea1-bfb7-7bb5d4762963"
path = "T-math/T-linear-algebra/T-vectors/L-basis/F-01-introduction"
format = "md"
location = "T-math/T-linear-algebra/T-vectors/L-basis/F-01-introduction.md"

[[route]]
id = "07ff1a0b-e84f-40bb-996f-467a03d2bf3c"
path = "T-math/T-linear-algebra/T-vectors/L-reflection/F-01-introduction"
format = "md"
location = "T-math/T-linear-algebra/T-vectors/L-reflection/F-01-introduction.md"
